/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.instil.ibe;

public class ibe {
  public static void IBE_init() {
    ibeJNI.IBE_init();
  }

  public static void IBE_clear() {
    ibeJNI.IBE_clear();
  }

  public static void params_out(SWIGTYPE_p_FILE outfp, params_s params) {
    ibeJNI.params_out(SWIGTYPE_p_FILE.getCPtr(outfp), params_s.getCPtr(params), params);
  }

  public static void params_clear(params_s params) {
    ibeJNI.params_clear(params_s.getCPtr(params), params);
  }

  public static void params_robust_clear(params_s params) {
    ibeJNI.params_robust_clear(params_s.getCPtr(params), params);
  }

  public static void IBE_setup(params_s params, SWIGTYPE_p_byte_string_t master, int k, int qk, String system) {
    ibeJNI.IBE_setup(params_s.getCPtr(params), params, SWIGTYPE_p_byte_string_t.getCPtr(master), k, qk, system);
  }

  public static void IBE_extract(SWIGTYPE_p_byte_string_t key, SWIGTYPE_p_byte_string_t master, String id, params_s params) {
    ibeJNI.IBE_extract(SWIGTYPE_p_byte_string_t.getCPtr(key), SWIGTYPE_p_byte_string_t.getCPtr(master), id, params_s.getCPtr(params), params);
  }

  public static void IBE_split_master(SWIGTYPE_p_byte_string_t mshare, SWIGTYPE_p_byte_string_t master, int t, int n, params_s params) {
    ibeJNI.IBE_split_master(SWIGTYPE_p_byte_string_t.getCPtr(mshare), SWIGTYPE_p_byte_string_t.getCPtr(master), t, n, params_s.getCPtr(params), params);
  }

  public static int IBE_construct_master(SWIGTYPE_p_byte_string_t master, SWIGTYPE_p_byte_string_t mshare, params_s params) {
    return ibeJNI.IBE_construct_master(SWIGTYPE_p_byte_string_t.getCPtr(master), SWIGTYPE_p_byte_string_t.getCPtr(mshare), params_s.getCPtr(params), params);
  }

  public static int IBE_serialize_params(SWIGTYPE_p_byte_string_t bs, params_s params) {
    return ibeJNI.IBE_serialize_params(SWIGTYPE_p_byte_string_t.getCPtr(bs), params_s.getCPtr(params), params);
  }

  public static int IBE_deserialize_params(params_s params, SWIGTYPE_p_byte_string_t bs) {
    return ibeJNI.IBE_deserialize_params(params_s.getCPtr(params), params, SWIGTYPE_p_byte_string_t.getCPtr(bs));
  }

  public static void IBE_extract_share(SWIGTYPE_p_byte_string_t share, SWIGTYPE_p_byte_string_t master_share, String id, params_s params) {
    ibeJNI.IBE_extract_share(SWIGTYPE_p_byte_string_t.getCPtr(share), SWIGTYPE_p_byte_string_t.getCPtr(master_share), id, params_s.getCPtr(params), params);
  }

  public static int IBE_combine(SWIGTYPE_p_byte_string_t key, SWIGTYPE_p_byte_string_t kshare, params_s params) {
    return ibeJNI.IBE_combine(SWIGTYPE_p_byte_string_t.getCPtr(key), SWIGTYPE_p_byte_string_t.getCPtr(kshare), params_s.getCPtr(params), params);
  }

  public static int IBE_threshold(params_s params) {
    return ibeJNI.IBE_threshold(params_s.getCPtr(params), params);
  }

  public static int IBE_sharecount(params_s params) {
    return ibeJNI.IBE_sharecount(params_s.getCPtr(params), params);
  }

  public static String IBE_system(params_s params) {
    return ibeJNI.IBE_system(params_s.getCPtr(params), params);
  }

  public static String IBE_version(params_s params) {
    return ibeJNI.IBE_version(params_s.getCPtr(params), params);
  }

  public static void IBE_KEM_encrypt_array(SWIGTYPE_p_byte_string_t secret, SWIGTYPE_p_byte_string_t U, SWIGTYPE_p_p_char idarray, int count, params_s params) {
    ibeJNI.IBE_KEM_encrypt_array(SWIGTYPE_p_byte_string_t.getCPtr(secret), SWIGTYPE_p_byte_string_t.getCPtr(U), SWIGTYPE_p_p_char.getCPtr(idarray), count, params_s.getCPtr(params), params);
  }

  public static void IBE_KEM_encrypt(SWIGTYPE_p_byte_string_t secret, SWIGTYPE_p_byte_string_t U, String id, params_s params) {
    ibeJNI.IBE_KEM_encrypt(SWIGTYPE_p_byte_string_t.getCPtr(secret), SWIGTYPE_p_byte_string_t.getCPtr(U), id, params_s.getCPtr(params), params);
  }

  public static void IBE_KEM_decrypt(SWIGTYPE_p_byte_string_t secret, SWIGTYPE_p_byte_string_t U, SWIGTYPE_p_byte_string_t key, params_s params) {
    ibeJNI.IBE_KEM_decrypt(SWIGTYPE_p_byte_string_t.getCPtr(secret), SWIGTYPE_p_byte_string_t.getCPtr(U), SWIGTYPE_p_byte_string_t.getCPtr(key), params_s.getCPtr(params), params);
  }

  public static int IBE_hide_key_array(SWIGTYPE_p_byte_string_t U, SWIGTYPE_p_byte_string_t V, SWIGTYPE_p_p_char id, int idcount, SWIGTYPE_p_byte_string_t K, params_s params) {
    return ibeJNI.IBE_hide_key_array(SWIGTYPE_p_byte_string_t.getCPtr(U), SWIGTYPE_p_byte_string_t.getCPtr(V), SWIGTYPE_p_p_char.getCPtr(id), idcount, SWIGTYPE_p_byte_string_t.getCPtr(K), params_s.getCPtr(params), params);
  }

  public static int IBE_hide_key(SWIGTYPE_p_byte_string_t U, SWIGTYPE_p_byte_string_t V, String id, SWIGTYPE_p_byte_string_t K, params_s params) {
    return ibeJNI.IBE_hide_key(SWIGTYPE_p_byte_string_t.getCPtr(U), SWIGTYPE_p_byte_string_t.getCPtr(V), id, SWIGTYPE_p_byte_string_t.getCPtr(K), params_s.getCPtr(params), params);
  }

  public static int IBE_reveal_key(SWIGTYPE_p_byte_string_t K, SWIGTYPE_p_byte_string_t U, SWIGTYPE_p_byte_string_t V, SWIGTYPE_p_byte_string_t privkey, params_s params) {
    return ibeJNI.IBE_reveal_key(SWIGTYPE_p_byte_string_t.getCPtr(K), SWIGTYPE_p_byte_string_t.getCPtr(U), SWIGTYPE_p_byte_string_t.getCPtr(V), SWIGTYPE_p_byte_string_t.getCPtr(privkey), params_s.getCPtr(params), params);
  }

  public static void IBE_get_shared_secret(SWIGTYPE_p_byte_string_t s, String id, SWIGTYPE_p_byte_string_t key, params_s params) {
    ibeJNI.IBE_get_shared_secret(SWIGTYPE_p_byte_string_t.getCPtr(s), id, SWIGTYPE_p_byte_string_t.getCPtr(key), params_s.getCPtr(params), params);
  }

  public static void preprocessed_key_init(preprocessed_key_s pk, params_s params) {
    ibeJNI.preprocessed_key_init(preprocessed_key_s.getCPtr(pk), pk, params_s.getCPtr(params), params);
  }

  public static void preprocessed_key_clear(preprocessed_key_s pk) {
    ibeJNI.preprocessed_key_clear(preprocessed_key_s.getCPtr(pk), pk);
  }

  public static void IBE_get_shared_secret_preprocess(preprocessed_key_s pk, SWIGTYPE_p_byte_string_t key, params_s params) {
    ibeJNI.IBE_get_shared_secret_preprocess(preprocessed_key_s.getCPtr(pk), pk, SWIGTYPE_p_byte_string_t.getCPtr(key), params_s.getCPtr(params), params);
  }

  public static void IBE_get_shared_secret_postprocess(SWIGTYPE_p_byte_string_t s, String id, preprocessed_key_s pk, params_s params) {
    ibeJNI.IBE_get_shared_secret_postprocess(SWIGTYPE_p_byte_string_t.getCPtr(s), id, preprocessed_key_s.getCPtr(pk), pk, params_s.getCPtr(params), params);
  }

  public static void BLS_keygen(SWIGTYPE_p_byte_string_t privkey, SWIGTYPE_p_byte_string_t pubkey, params_s params) {
    ibeJNI.BLS_keygen(SWIGTYPE_p_byte_string_t.getCPtr(privkey), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), params_s.getCPtr(params), params);
  }

  public static void BLS_sign(SWIGTYPE_p_byte_string_t sig, SWIGTYPE_p_byte_string_t message, SWIGTYPE_p_byte_string_t key, params_s params) {
    ibeJNI.BLS_sign(SWIGTYPE_p_byte_string_t.getCPtr(sig), SWIGTYPE_p_byte_string_t.getCPtr(message), SWIGTYPE_p_byte_string_t.getCPtr(key), params_s.getCPtr(params), params);
  }

  public static int BLS_verify(SWIGTYPE_p_byte_string_t sig, SWIGTYPE_p_byte_string_t message, SWIGTYPE_p_byte_string_t pubkey, params_s params) {
    return ibeJNI.BLS_verify(SWIGTYPE_p_byte_string_t.getCPtr(sig), SWIGTYPE_p_byte_string_t.getCPtr(message), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), params_s.getCPtr(params), params);
  }

  public static void IBE_keygen(SWIGTYPE_p_byte_string_t privkey, SWIGTYPE_p_byte_string_t pubkey, params_s params) {
    ibeJNI.IBE_keygen(SWIGTYPE_p_byte_string_t.getCPtr(privkey), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), params_s.getCPtr(params), params);
  }

  public static void IBE_certify_share(SWIGTYPE_p_byte_string_t share, SWIGTYPE_p_byte_string_t mshare, SWIGTYPE_p_byte_string_t pubkey, String id, params_s params) {
    ibeJNI.IBE_certify_share(SWIGTYPE_p_byte_string_t.getCPtr(share), SWIGTYPE_p_byte_string_t.getCPtr(mshare), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), id, params_s.getCPtr(params), params);
  }

  public static void IBE_certify(SWIGTYPE_p_byte_string_t cert, SWIGTYPE_p_byte_string_t master, SWIGTYPE_p_byte_string_t pubkey, String id, params_s params) {
    ibeJNI.IBE_certify(SWIGTYPE_p_byte_string_t.getCPtr(cert), SWIGTYPE_p_byte_string_t.getCPtr(master), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), id, params_s.getCPtr(params), params);
  }

  public static void IBE_sign(SWIGTYPE_p_byte_string_t sig, SWIGTYPE_p_byte_string_t message, SWIGTYPE_p_byte_string_t privkey, SWIGTYPE_p_byte_string_t cert, params_s params) {
    ibeJNI.IBE_sign(SWIGTYPE_p_byte_string_t.getCPtr(sig), SWIGTYPE_p_byte_string_t.getCPtr(message), SWIGTYPE_p_byte_string_t.getCPtr(privkey), SWIGTYPE_p_byte_string_t.getCPtr(cert), params_s.getCPtr(params), params);
  }

  public static int IBE_verify(SWIGTYPE_p_byte_string_t sig, SWIGTYPE_p_byte_string_t message, SWIGTYPE_p_byte_string_t pubkey, String id, params_s params) {
    return ibeJNI.IBE_verify(SWIGTYPE_p_byte_string_t.getCPtr(sig), SWIGTYPE_p_byte_string_t.getCPtr(message), SWIGTYPE_p_byte_string_t.getCPtr(pubkey), id, params_s.getCPtr(params), params);
  }

  public static int decrypt(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.decrypt(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int encrypt(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.encrypt(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int request(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.request(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int combine(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.combine(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int imratio(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.imratio(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int extract_share(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.extract_share(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int key_from_master_shares(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.key_from_master_shares(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int fixed_password_decrypt(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.fixed_password_decrypt(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int my_decrypt(int argc, SWIGTYPE_p_p_char argv) {
    return ibeJNI.my_decrypt(argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static void setCnfctx(SWIGTYPE_p_CONF_CTX value) {
    ibeJNI.cnfctx_set(SWIGTYPE_p_CONF_CTX.getCPtr(value));
  }

  public static SWIGTYPE_p_CONF_CTX getCnfctx() {
    long cPtr = ibeJNI.cnfctx_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_CONF_CTX(cPtr, false);
  }

  public static void setParams(params_s value) {
    ibeJNI.params_set(params_s.getCPtr(value), value);
  }

  public static params_s getParams() {
    long cPtr = ibeJNI.params_get();
    return (cPtr == 0) ? null : new params_s(cPtr, false);
  }

}
