/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.instil.ibe;

public class ibeJNI {
  public final static native void params_s_id_set(long jarg1, params_s jarg1_, String jarg2);
  public final static native String params_s_id_get(long jarg1, params_s jarg1_);
  public final static native void params_s_version_set(long jarg1, params_s jarg1_, String jarg2);
  public final static native String params_s_version_get(long jarg1, params_s jarg1_);
  public final static native void params_s_p_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_p_get(long jarg1, params_s jarg1_);
  public final static native void params_s_q_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_q_get(long jarg1, params_s jarg1_);
  public final static native void params_s_P_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_P_get(long jarg1, params_s jarg1_);
  public final static native void params_s_Ppub_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_Ppub_get(long jarg1, params_s jarg1_);
  public final static native void params_s_curve_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_curve_get(long jarg1, params_s jarg1_);
  public final static native void params_s_sharet_set(long jarg1, params_s jarg1_, int jarg2);
  public final static native int params_s_sharet_get(long jarg1, params_s jarg1_);
  public final static native void params_s_sharen_set(long jarg1, params_s jarg1_, int jarg2);
  public final static native int params_s_sharen_get(long jarg1, params_s jarg1_);
  public final static native void params_s_robustx_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_robustx_get(long jarg1, params_s jarg1_);
  public final static native void params_s_robustP_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_robustP_get(long jarg1, params_s jarg1_);
  public final static native void params_s_p1onq_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_p1onq_get(long jarg1, params_s jarg1_);
  public final static native void params_s_zeta_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_zeta_get(long jarg1, params_s jarg1_);
  public final static native void params_s_PhiPpub_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_PhiPpub_get(long jarg1, params_s jarg1_);
  public final static native void params_s_Ppub_mc_set(long jarg1, params_s jarg1_, long jarg2);
  public final static native long params_s_Ppub_mc_get(long jarg1, params_s jarg1_);
  public final static native long new_params_s();
  public final static native void delete_params_s(long jarg1);
  public final static native void IBE_init();
  public final static native void IBE_clear();
  public final static native void params_out(long jarg1, long jarg2, params_s jarg2_);
  public final static native void params_clear(long jarg1, params_s jarg1_);
  public final static native void params_robust_clear(long jarg1, params_s jarg1_);
  public final static native void IBE_setup(long jarg1, params_s jarg1_, long jarg2, int jarg3, int jarg4, String jarg5);
  public final static native void IBE_extract(long jarg1, long jarg2, String jarg3, long jarg4, params_s jarg4_);
  public final static native void IBE_split_master(long jarg1, long jarg2, int jarg3, int jarg4, long jarg5, params_s jarg5_);
  public final static native int IBE_construct_master(long jarg1, long jarg2, long jarg3, params_s jarg3_);
  public final static native int IBE_serialize_params(long jarg1, long jarg2, params_s jarg2_);
  public final static native int IBE_deserialize_params(long jarg1, params_s jarg1_, long jarg2);
  public final static native void IBE_extract_share(long jarg1, long jarg2, String jarg3, long jarg4, params_s jarg4_);
  public final static native int IBE_combine(long jarg1, long jarg2, long jarg3, params_s jarg3_);
  public final static native int IBE_threshold(long jarg1, params_s jarg1_);
  public final static native int IBE_sharecount(long jarg1, params_s jarg1_);
  public final static native String IBE_system(long jarg1, params_s jarg1_);
  public final static native String IBE_version(long jarg1, params_s jarg1_);
  public final static native void IBE_KEM_encrypt_array(long jarg1, long jarg2, long jarg3, int jarg4, long jarg5, params_s jarg5_);
  public final static native void IBE_KEM_encrypt(long jarg1, long jarg2, String jarg3, long jarg4, params_s jarg4_);
  public final static native void IBE_KEM_decrypt(long jarg1, long jarg2, long jarg3, long jarg4, params_s jarg4_);
  public final static native int IBE_hide_key_array(long jarg1, long jarg2, long jarg3, int jarg4, long jarg5, long jarg6, params_s jarg6_);
  public final static native int IBE_hide_key(long jarg1, long jarg2, String jarg3, long jarg4, long jarg5, params_s jarg5_);
  public final static native int IBE_reveal_key(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, params_s jarg5_);
  public final static native void IBE_get_shared_secret(long jarg1, String jarg2, long jarg3, long jarg4, params_s jarg4_);
  public final static native void preprocessed_key_s_mc_set(long jarg1, preprocessed_key_s jarg1_, long jarg2);
  public final static native long preprocessed_key_s_mc_get(long jarg1, preprocessed_key_s jarg1_);
  public final static native long new_preprocessed_key_s();
  public final static native void delete_preprocessed_key_s(long jarg1);
  public final static native void preprocessed_key_init(long jarg1, preprocessed_key_s jarg1_, long jarg2, params_s jarg2_);
  public final static native void preprocessed_key_clear(long jarg1, preprocessed_key_s jarg1_);
  public final static native void IBE_get_shared_secret_preprocess(long jarg1, preprocessed_key_s jarg1_, long jarg2, long jarg3, params_s jarg3_);
  public final static native void IBE_get_shared_secret_postprocess(long jarg1, String jarg2, long jarg3, preprocessed_key_s jarg3_, long jarg4, params_s jarg4_);
  public final static native void BLS_keygen(long jarg1, long jarg2, long jarg3, params_s jarg3_);
  public final static native void BLS_sign(long jarg1, long jarg2, long jarg3, long jarg4, params_s jarg4_);
  public final static native int BLS_verify(long jarg1, long jarg2, long jarg3, long jarg4, params_s jarg4_);
  public final static native void IBE_keygen(long jarg1, long jarg2, long jarg3, params_s jarg3_);
  public final static native void IBE_certify_share(long jarg1, long jarg2, long jarg3, String jarg4, long jarg5, params_s jarg5_);
  public final static native void IBE_certify(long jarg1, long jarg2, long jarg3, String jarg4, long jarg5, params_s jarg5_);
  public final static native void IBE_sign(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, params_s jarg5_);
  public final static native int IBE_verify(long jarg1, long jarg2, long jarg3, String jarg4, long jarg5, params_s jarg5_);
  public final static native int decrypt(int jarg1, long jarg2);
  public final static native int encrypt(int jarg1, long jarg2);
  public final static native int request(int jarg1, long jarg2);
  public final static native int combine(int jarg1, long jarg2);
  public final static native int imratio(int jarg1, long jarg2);
  public final static native int extract_share(int jarg1, long jarg2);
  public final static native int key_from_master_shares(int jarg1, long jarg2);
  public final static native int fixed_password_decrypt(int jarg1, long jarg2);
  public final static native int my_decrypt(int jarg1, long jarg2);
  public final static native void cnfctx_set(long jarg1);
  public final static native long cnfctx_get();
  public final static native void params_set(long jarg1, params_s jarg1_);
  public final static native long params_get();
}
