/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.instil.ibe;

public class params_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected params_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(params_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ibeJNI.delete_params_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(String value) {
    ibeJNI.params_s_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return ibeJNI.params_s_id_get(swigCPtr, this);
  }

  public void setVersion(String value) {
    ibeJNI.params_s_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return ibeJNI.params_s_version_get(swigCPtr, this);
  }

  public void setP(SWIGTYPE_p_mpz_t value) {
    ibeJNI.params_s_p_set(swigCPtr, this, SWIGTYPE_p_mpz_t.getCPtr(value));
  }

  public SWIGTYPE_p_mpz_t getP() {
    return new SWIGTYPE_p_mpz_t(ibeJNI.params_s_p_get(swigCPtr, this), true);
  }

  public void setQ(SWIGTYPE_p_mpz_t value) {
    ibeJNI.params_s_q_set(swigCPtr, this, SWIGTYPE_p_mpz_t.getCPtr(value));
  }

  public SWIGTYPE_p_mpz_t getQ() {
    return new SWIGTYPE_p_mpz_t(ibeJNI.params_s_q_get(swigCPtr, this), true);
  }

  public void setP(SWIGTYPE_p_point_t value) {
    ibeJNI.params_s_P_set(swigCPtr, this, SWIGTYPE_p_point_t.getCPtr(value));
  }

  public SWIGTYPE_p_point_t getP() {
    return new SWIGTYPE_p_point_t(ibeJNI.params_s_P_get(swigCPtr, this), true);
  }

  public void setPpub(SWIGTYPE_p_point_t value) {
    ibeJNI.params_s_Ppub_set(swigCPtr, this, SWIGTYPE_p_point_t.getCPtr(value));
  }

  public SWIGTYPE_p_point_t getPpub() {
    return new SWIGTYPE_p_point_t(ibeJNI.params_s_Ppub_get(swigCPtr, this), true);
  }

  public void setCurve(SWIGTYPE_p_curve_t value) {
    ibeJNI.params_s_curve_set(swigCPtr, this, SWIGTYPE_p_curve_t.getCPtr(value));
  }

  public SWIGTYPE_p_curve_t getCurve() {
    return new SWIGTYPE_p_curve_t(ibeJNI.params_s_curve_get(swigCPtr, this), true);
  }

  public void setSharet(int value) {
    ibeJNI.params_s_sharet_set(swigCPtr, this, value);
  }

  public int getSharet() {
    return ibeJNI.params_s_sharet_get(swigCPtr, this);
  }

  public void setSharen(int value) {
    ibeJNI.params_s_sharen_set(swigCPtr, this, value);
  }

  public int getSharen() {
    return ibeJNI.params_s_sharen_get(swigCPtr, this);
  }

  public void setRobustx(SWIGTYPE_p_mpz_t value) {
    ibeJNI.params_s_robustx_set(swigCPtr, this, SWIGTYPE_p_mpz_t.getCPtr(value));
  }

  public SWIGTYPE_p_mpz_t getRobustx() {
    long cPtr = ibeJNI.params_s_robustx_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mpz_t(cPtr, false);
  }

  public void setRobustP(SWIGTYPE_p_point_t value) {
    ibeJNI.params_s_robustP_set(swigCPtr, this, SWIGTYPE_p_point_t.getCPtr(value));
  }

  public SWIGTYPE_p_point_t getRobustP() {
    long cPtr = ibeJNI.params_s_robustP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_point_t(cPtr, false);
  }

  public void setP1onq(SWIGTYPE_p_mpz_t value) {
    ibeJNI.params_s_p1onq_set(swigCPtr, this, SWIGTYPE_p_mpz_t.getCPtr(value));
  }

  public SWIGTYPE_p_mpz_t getP1onq() {
    return new SWIGTYPE_p_mpz_t(ibeJNI.params_s_p1onq_get(swigCPtr, this), true);
  }

  public void setZeta(SWIGTYPE_p_fp2_t value) {
    ibeJNI.params_s_zeta_set(swigCPtr, this, SWIGTYPE_p_fp2_t.getCPtr(value));
  }

  public SWIGTYPE_p_fp2_t getZeta() {
    return new SWIGTYPE_p_fp2_t(ibeJNI.params_s_zeta_get(swigCPtr, this), true);
  }

  public void setPhiPpub(SWIGTYPE_p_point_t value) {
    ibeJNI.params_s_PhiPpub_set(swigCPtr, this, SWIGTYPE_p_point_t.getCPtr(value));
  }

  public SWIGTYPE_p_point_t getPhiPpub() {
    return new SWIGTYPE_p_point_t(ibeJNI.params_s_PhiPpub_get(swigCPtr, this), true);
  }

  public void setPpub_mc(SWIGTYPE_p_miller_cache_t value) {
    ibeJNI.params_s_Ppub_mc_set(swigCPtr, this, SWIGTYPE_p_miller_cache_t.getCPtr(value));
  }

  public SWIGTYPE_p_miller_cache_t getPpub_mc() {
    return new SWIGTYPE_p_miller_cache_t(ibeJNI.params_s_Ppub_mc_get(swigCPtr, this), true);
  }

  public params_s() {
    this(ibeJNI.new_params_s(), true);
  }

}
