/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.instil.ibe;

public class preprocessed_key_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected preprocessed_key_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(preprocessed_key_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ibeJNI.delete_preprocessed_key_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMc(SWIGTYPE_p_miller_cache_t value) {
    ibeJNI.preprocessed_key_s_mc_set(swigCPtr, this, SWIGTYPE_p_miller_cache_t.getCPtr(value));
  }

  public SWIGTYPE_p_miller_cache_t getMc() {
    return new SWIGTYPE_p_miller_cache_t(ibeJNI.preprocessed_key_s_mc_get(swigCPtr, this), true);
  }

  public preprocessed_key_s() {
    this(ibeJNI.new_preprocessed_key_s(), true);
  }

}
