/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "ibe.h"
#include "ibe_progs.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->id);
    if (arg2) {
      arg1->id = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->id, (const char *)arg2);
    } else {
      arg1->id = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (char *) ((arg1)->id);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->version);
    if (arg2) {
      arg1->version = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->version, (const char *)arg2);
    } else {
      arg1->version = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (char *) ((arg1)->version);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1p_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t arg2 ;
  mpz_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(mpz_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mpz_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->p = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1p_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->p);
  {
    mpz_t * resultptr = (mpz_t *) malloc(sizeof(mpz_t));
    memmove(resultptr, &result, sizeof(mpz_t));
    *(mpz_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1q_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t arg2 ;
  mpz_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(mpz_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mpz_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->q = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1q_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->q);
  {
    mpz_t * resultptr = (mpz_t *) malloc(sizeof(mpz_t));
    memmove(resultptr, &result, sizeof(mpz_t));
    *(mpz_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1P_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t arg2 ;
  point_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(point_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null point_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->P = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1P_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->P);
  {
    point_t * resultptr = (point_t *) malloc(sizeof(point_t));
    memmove(resultptr, &result, sizeof(point_t));
    *(point_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1Ppub_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t arg2 ;
  point_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(point_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null point_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Ppub = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1Ppub_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->Ppub);
  {
    point_t * resultptr = (point_t *) malloc(sizeof(point_t));
    memmove(resultptr, &result, sizeof(point_t));
    *(point_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1curve_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  curve_t arg2 ;
  curve_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(curve_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null curve_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->curve = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1curve_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  curve_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->curve);
  {
    curve_t * resultptr = (curve_t *) malloc(sizeof(curve_t));
    memmove(resultptr, &result, sizeof(curve_t));
    *(curve_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1sharet_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->sharet = arg2;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1sharet_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (int) ((arg1)->sharet);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1sharen_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->sharen = arg2;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1sharen_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (int) ((arg1)->sharen);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1robustx_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t *arg2 = (mpz_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = *(mpz_t **)&jarg2; 
  if (arg1) (arg1)->robustx = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1robustx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (mpz_t *) ((arg1)->robustx);
  *(mpz_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1robustP_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t *arg2 = (point_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  arg2 = *(point_t **)&jarg2; 
  if (arg1) (arg1)->robustP = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1robustP_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (point_t *) ((arg1)->robustP);
  *(point_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1p1onq_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t arg2 ;
  mpz_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(mpz_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null mpz_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->p1onq = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1p1onq_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  mpz_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->p1onq);
  {
    mpz_t * resultptr = (mpz_t *) malloc(sizeof(mpz_t));
    memmove(resultptr, &result, sizeof(mpz_t));
    *(mpz_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1zeta_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  fp2_t arg2 ;
  fp2_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(fp2_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null fp2_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->zeta = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1zeta_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  fp2_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->zeta);
  {
    fp2_t * resultptr = (fp2_t *) malloc(sizeof(fp2_t));
    memmove(resultptr, &result, sizeof(fp2_t));
    *(fp2_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1PhiPpub_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t arg2 ;
  point_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(point_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null point_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->PhiPpub = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1PhiPpub_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  point_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->PhiPpub);
  {
    point_t * resultptr = (point_t *) malloc(sizeof(point_t));
    memmove(resultptr, &result, sizeof(point_t));
    *(point_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1Ppub_1mc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  miller_cache_t arg2 ;
  miller_cache_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(miller_cache_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null miller_cache_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Ppub_mc = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1s_1Ppub_1mc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct params_s *arg1 = (struct params_s *) 0 ;
  miller_cache_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result =  ((arg1)->Ppub_mc);
  {
    miller_cache_t * resultptr = (miller_cache_t *) malloc(sizeof(miller_cache_t));
    memmove(resultptr, &result, sizeof(miller_cache_t));
    *(miller_cache_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_new_1params_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct params_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct params_s *)calloc(1, sizeof(struct params_s));
  *(struct params_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_delete_1params_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct params_s *arg1 = (struct params_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct params_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1init(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  IBE_init();
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  IBE_clear();
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1out(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  FILE *arg1 = (FILE *) 0 ;
  struct params_s *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(FILE **)&jarg1; 
  arg2 = *(struct params_s **)&jarg2; 
  params_out(arg1,arg2);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct params_s *arg1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  params_clear(arg1);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1robust_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct params_s *arg1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  params_robust_clear(arg1);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1setup(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jint jarg4, jstring jarg5) {
  struct params_s *arg1 ;
  byte_string_t arg2 ;
  int arg3 ;
  int arg4 ;
  char *arg5 = (char *) 0 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return ;
  }
  IBE_setup(arg1,arg2,arg3,arg4,arg5);
  
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1extract(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  char *arg3 = (char *) 0 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = *(struct params_s **)&jarg4; 
  IBE_extract(arg1,arg2,(char const *)arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1split_1master(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jlong jarg5, jobject jarg5_) {
  byte_string_t *arg1 = (byte_string_t *) 0 ;
  byte_string_t arg2 ;
  int arg3 ;
  int arg4 ;
  struct params_s *arg5 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(byte_string_t **)&jarg1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(struct params_s **)&jarg5; 
  IBE_split_master(arg1,arg2,arg3,arg4,arg5);
  
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1construct_1master(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t *arg2 = (byte_string_t *) 0 ;
  struct params_s *arg3 ;
  byte_string_t *argp1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(byte_string_t **)&jarg2; 
  arg3 = *(struct params_s **)&jarg3; 
  result = (int)IBE_construct_master(arg1,arg2,arg3);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1serialize_1params(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  struct params_s *arg2 ;
  byte_string_t *argp1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(struct params_s **)&jarg2; 
  result = (int)IBE_serialize_params(arg1,arg2);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1deserialize_1params(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  struct params_s *arg1 ;
  byte_string_t arg2 ;
  byte_string_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (int)IBE_deserialize_params(arg1,arg2);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1extract_1share(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  char *arg3 = (char *) 0 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = *(struct params_s **)&jarg4; 
  IBE_extract_share(arg1,arg2,(char const *)arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1combine(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t *arg2 = (byte_string_t *) 0 ;
  struct params_s *arg3 ;
  byte_string_t *argp1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(byte_string_t **)&jarg2; 
  arg3 = *(struct params_s **)&jarg3; 
  result = (int)IBE_combine(arg1,arg2,arg3);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1threshold(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct params_s *arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (int)IBE_threshold(arg1);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1sharecount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct params_s *arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (int)IBE_sharecount(arg1);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_instil_ibe_ibeJNI_IBE_1system(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct params_s *arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (char *)IBE_system(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_instil_ibe_ibeJNI_IBE_1version(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct params_s *arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  result = (char *)IBE_version(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1KEM_1encrypt_1array(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jlong jarg5, jobject jarg5_) {
  byte_string_t *arg1 = (byte_string_t *) 0 ;
  byte_string_t arg2 ;
  char **arg3 = (char **) 0 ;
  int arg4 ;
  struct params_s *arg5 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(byte_string_t **)&jarg1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(struct params_s **)&jarg5; 
  IBE_KEM_encrypt_array(arg1,arg2,arg3,arg4,arg5);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1KEM_1encrypt(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  char *arg3 = (char *) 0 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = *(struct params_s **)&jarg4; 
  IBE_KEM_encrypt(arg1,arg2,arg3,arg4);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1KEM_1decrypt(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  arg4 = *(struct params_s **)&jarg4; 
  IBE_KEM_decrypt(arg1,arg2,arg3,arg4);
  
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1hide_1key_1array(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t *arg2 = (byte_string_t *) 0 ;
  char **arg3 = (char **) 0 ;
  int arg4 ;
  byte_string_t arg5 ;
  struct params_s *arg6 ;
  byte_string_t *argp1 ;
  byte_string_t *argp5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  arg2 = *(byte_string_t **)&jarg2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = (int)jarg4; 
  argp5 = *(byte_string_t **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg5 = *argp5; 
  arg6 = *(struct params_s **)&jarg6; 
  result = (int)IBE_hide_key_array(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1hide_1key(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  char *arg3 = (char *) 0 ;
  byte_string_t arg4 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  argp4 = *(byte_string_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(struct params_s **)&jarg5; 
  result = (int)IBE_hide_key(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1reveal_1key(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  byte_string_t arg4 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  byte_string_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(byte_string_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = *(struct params_s **)&jarg5; 
  result = (int)IBE_reveal_key(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1get_1shared_1secret(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  char *arg2 = (char *) 0 ;
  byte_string_t arg3 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  arg4 = *(struct params_s **)&jarg4; 
  IBE_get_shared_secret(arg1,arg2,arg3,arg4);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_preprocessed_1key_1s_1mc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct preprocessed_key_s *arg1 = (struct preprocessed_key_s *) 0 ;
  miller_cache_t arg2 ;
  miller_cache_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  argp2 = *(miller_cache_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null miller_cache_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->mc = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_preprocessed_1key_1s_1mc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct preprocessed_key_s *arg1 = (struct preprocessed_key_s *) 0 ;
  miller_cache_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  result =  ((arg1)->mc);
  {
    miller_cache_t * resultptr = (miller_cache_t *) malloc(sizeof(miller_cache_t));
    memmove(resultptr, &result, sizeof(miller_cache_t));
    *(miller_cache_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_new_1preprocessed_1key_1s(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct preprocessed_key_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct preprocessed_key_s *)calloc(1, sizeof(struct preprocessed_key_s));
  *(struct preprocessed_key_s **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_delete_1preprocessed_1key_1s(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct preprocessed_key_s *arg1 = (struct preprocessed_key_s *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_preprocessed_1key_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct preprocessed_key_s *arg1 ;
  struct params_s *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  arg2 = *(struct params_s **)&jarg2; 
  preprocessed_key_init(arg1,arg2);
  
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_preprocessed_1key_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct preprocessed_key_s *arg1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  preprocessed_key_clear(arg1);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1get_1shared_1secret_1preprocess(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jobject jarg3_) {
  struct preprocessed_key_s *arg1 ;
  byte_string_t arg2 ;
  struct params_s *arg3 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(struct preprocessed_key_s **)&jarg1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = *(struct params_s **)&jarg3; 
  IBE_get_shared_secret_preprocess(arg1,arg2,arg3);
  
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1get_1shared_1secret_1postprocess(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jobject jarg3_, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  char *arg2 = (char *) 0 ;
  struct preprocessed_key_s *arg3 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = *(struct preprocessed_key_s **)&jarg3; 
  arg4 = *(struct params_s **)&jarg4; 
  IBE_get_shared_secret_postprocess(arg1,arg2,arg3,arg4);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_BLS_1keygen(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  struct params_s *arg3 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = *(struct params_s **)&jarg3; 
  BLS_keygen(arg1,arg2,arg3);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_BLS_1sign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  arg4 = *(struct params_s **)&jarg4; 
  BLS_sign(arg1,arg2,arg3,arg4);
  
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_BLS_1verify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  struct params_s *arg4 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(struct params_s **)&jarg4; 
  result = (int)BLS_verify(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1keygen(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  struct params_s *arg3 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  arg3 = *(struct params_s **)&jarg3; 
  IBE_keygen(arg1,arg2,arg3);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1certify_1share(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jlong jarg5, jobject jarg5_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  char *arg4 = (char *) 0 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return ;
  }
  arg5 = *(struct params_s **)&jarg5; 
  IBE_certify_share(arg1,arg2,arg3,(char const *)arg4,arg5);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1certify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jlong jarg5, jobject jarg5_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  char *arg4 = (char *) 0 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return ;
  }
  arg5 = *(struct params_s **)&jarg5; 
  IBE_certify(arg1,arg2,arg3,(char const *)arg4,arg5);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_IBE_1sign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  byte_string_t arg4 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  byte_string_t *argp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(byte_string_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return ;
  }
  arg4 = *argp4; 
  arg5 = *(struct params_s **)&jarg5; 
  IBE_sign(arg1,arg2,arg3,arg4,arg5);
  
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_IBE_1verify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jlong jarg5, jobject jarg5_) {
  jint jresult = 0 ;
  byte_string_t arg1 ;
  byte_string_t arg2 ;
  byte_string_t arg3 ;
  char *arg4 = (char *) 0 ;
  struct params_s *arg5 ;
  byte_string_t *argp1 ;
  byte_string_t *argp2 ;
  byte_string_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  argp1 = *(byte_string_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(byte_string_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(byte_string_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_string_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = *(struct params_s **)&jarg5; 
  result = (int)IBE_verify(arg1,arg2,arg3,(char const *)arg4,arg5);
  jresult = (jint)result; 
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_decrypt(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)decrypt(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_encrypt(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)encrypt(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_request(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)request(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_combine(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)combine(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_imratio(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)imratio(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_extract_1share(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)extract_share(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_key_1from_1master_1shares(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)key_from_master_shares(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_fixed_1password_1decrypt(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)fixed_password_decrypt(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_instil_ibe_ibeJNI_my_1decrypt(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)my_decrypt(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_cnfctx_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CONF_CTX *arg1 = (CONF_CTX *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CONF_CTX **)&jarg1; 
  cnfctx = arg1;
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_cnfctx_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CONF_CTX *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CONF_CTX *)cnfctx;
  *(CONF_CTX **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_instil_ibe_ibeJNI_params_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct params_s *arg1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct params_s **)&jarg1; 
  {
    size_t ii;
    struct params_s *b = (struct params_s *) params;
    for (ii = 0; ii < (size_t)1; ii++) b[ii] = *((struct params_s *) arg1 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_com_instil_ibe_ibeJNI_params_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct params_s *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct params_s *)params;
  *(struct params_s **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

