#!/bin/bash
i=1
while [ $i -lt 2 ]; do
    ./gen
    j=1
    while [ $j -lt 2 ]; do
	./ibe key_from_master_shares ha share
	#echo "Hello, World!" | ./ibe encrypt ben 
    echo "Assalamualaikum Dunia!" | ./ibe encrypt ha | ./ibe my_decrypt ha
	#echo "KCzpfOMgK3yxvqyMEn7qB4eb01re6Ck6qTcKUX6ZWbxBPP/uI86GLVdhWXE=" | ./ibe my_decrypt ben
	j=$((j+1))
    done
    i=$((i+1))
done
